import {
  HeartPulse,
  Plane,
  Gavel,
  FlaskConical,
  Palette,
  Flame,
  Rocket,
  BookOpen,
  Camera,
  Film,
  Hammer,
  TreePine,
  Laptop,
  ChefHat,
  Tractor,
  Atom,
  Building,
  Anchor,
  PenTool,
  Music,
} from 'lucide-react';
import type { Career, Student } from './types';

export const CAREERS: Career[] = [
  {
    id: 'doctor',
    name: 'Doctor',
    description: 'Diagnose and treat medical conditions.',
    theme: {
      backgroundColor: 'from-sky-100 to-sky-200',
      backgroundImage: 'radial-gradient(circle, rgba(255,255,255,0.7) 0%, rgba(224,242,254,0.5) 100%)',
      primaryColor: 'bg-red-500',
      textColor: 'text-slate-800',
      icon: HeartPulse,
      cursor: 'cursor-crosshair',
    },
  },
  {
    id: 'pilot',
    name: 'Pilot',
    description: 'Fly aircraft for airlines, corporations, or the military.',
    theme: {
      backgroundColor: 'from-blue-200 to-blue-300',
      backgroundImage: 'linear-gradient(to top, #a1c4fd 0%, #c2e9fb 100%)',
      primaryColor: 'bg-blue-700',
      textColor: 'text-white',
      icon: Plane,
      cursor: 'cursor-grab',
    },
  },
  {
    id: 'lawyer',
    name: 'Lawyer',
    description: 'Advise and represent clients in legal matters.',
    theme: {
      backgroundColor: 'from-gray-700 to-gray-800',
      backgroundImage: 'linear-gradient(to right, #434343 0%, black 100%)',
      primaryColor: 'bg-yellow-600',
      textColor: 'text-white',
      icon: Gavel,
      cursor: 'cursor-pointer',
    },
  },
  {
    id: 'scientist',
    name: 'Scientist',
    description: 'Conduct research to advance knowledge in a particular field.',
    theme: {
      backgroundColor: 'from-purple-100 to-purple-200',
      backgroundImage: 'linear-gradient(120deg, #e0c3fc 0%, #8ec5fc 100%)',
      primaryColor: 'bg-purple-600',
      textColor: 'text-purple-900',
      icon: FlaskConical,
      cursor: 'cursor-help',
    },
  },
  {
    id: 'artist',
    name: 'Artist',
    description: 'Create works of art, such as paintings, sculptures, or music.',
    theme: {
      backgroundColor: 'from-pink-100 to-yellow-100',
      backgroundImage: 'linear-gradient(to top, #ff9a9e 0%, #fecfef 99%, #fecfef 100%)',
      primaryColor: 'bg-pink-500',
      textColor: 'text-gray-800',
      icon: Palette,
      cursor: 'cursor-cell',
    },
  },
  {
    id: 'firefighter',
    name: 'Firefighter',
    description: 'Extinguish fires and rescue people from dangerous situations.',
    theme: {
      backgroundColor: 'from-red-500 to-orange-500',
      backgroundImage: 'linear-gradient(45deg, #ff9a9e 0%, #fad0c4 99%, #fad0c4 100%)',
      primaryColor: 'bg-yellow-400',
      textColor: 'text-white',
      icon: Flame,
      cursor: 'cursor-pointer',
    },
  },
  {
    id: 'astronaut',
    name: 'Astronaut',
    description: 'Travel into space to conduct research and explore.',
    theme: {
      backgroundColor: 'from-indigo-900 to-black',
      backgroundImage: 'linear-gradient(to top, #30cfd0 0%, #330867 100%)',
      primaryColor: 'bg-blue-400',
      textColor: 'text-gray-200',
      icon: Rocket,
      cursor: 'cursor-nesw-resize',
    },
  },
  {
    id: 'teacher',
    name: 'Teacher',
    description: 'Educate students in a variety of subjects.',
    theme: {
      backgroundColor: 'from-green-200 to-green-300',
      backgroundImage: 'linear-gradient(to top, #d2fbd3 0%, #d4fc79 100%)',
      primaryColor: 'bg-green-600',
      textColor: 'text-green-900',
      icon: BookOpen,
      cursor: 'cursor-text',
    },
  },
  {
    id: 'photographer',
    name: 'Photographer',
    description: 'Take pictures of people, places, and events.',
    theme: {
      backgroundColor: 'from-gray-300 to-gray-400',
      backgroundImage: 'linear-gradient(to top, #cfd9df 0%, #e2ebf0 100%)',
      primaryColor: 'bg-gray-800',
      textColor: 'text-gray-900',
      icon: Camera,
      cursor: 'cursor-zoom-in',
    },
  },
  {
    id: 'director',
    name: 'Film Director',
    description: 'Oversee the creative aspects of a film production.',
    theme: {
      backgroundColor: 'from-black to-gray-900',
      backgroundImage: 'linear-gradient(to right, #4158D0, #C850C0, #FFCC70)',
      primaryColor: 'bg-red-700',
      textColor: 'text-white',
      icon: Film,
      cursor: 'cursor-pointer',
    },
  },
  {
    id: 'builder',
    name: 'Builder',
    description: 'Construct and repair buildings and other structures.',
    theme: {
      backgroundColor: 'from-yellow-400 to-orange-400',
      backgroundImage: 'linear-gradient(to right, #f83600 0%, #f9d423 100%)',
      primaryColor: 'bg-gray-700',
      textColor: 'text-gray-800',
      icon: Hammer,
      cursor: 'cursor-pointer',
    },
  },
  {
    id: 'park_ranger',
    name: 'Park Ranger',
    description: 'Protect and manage national parks and forests.',
    theme: {
      backgroundColor: 'from-green-600 to-emerald-700',
      backgroundImage: 'linear-gradient(to top, #0ba360 0%, #3cba92 100%)',
      primaryColor: 'bg-yellow-700',
      textColor: 'text-white',
      icon: TreePine,
      cursor: 'cursor-pointer',
    },
  },
  {
    id: 'engineer',
    name: 'Software Engineer',
    description: 'Design, develop, and maintain software systems.',
    theme: {
      backgroundColor: 'from-gray-800 to-gray-900',
      backgroundImage: 'linear-gradient(to right, #243949 0%, #517fa4 100%)',
      primaryColor: 'bg-cyan-500',
      textColor: 'text-gray-200',
      icon: Laptop,
      cursor: 'cursor-progress',
    },
  },
  {
    id: 'chef',
    name: 'Chef',
    description: 'Create and prepare dishes in a restaurant or other establishment.',
    theme: {
      backgroundColor: 'from-white to-gray-100',
      backgroundImage: 'linear-gradient(120deg, #fdfbfb 0%, #ebedee 100%)',
      primaryColor: 'bg-red-600',
      textColor: 'text-gray-800',
      icon: ChefHat,
      cursor: 'cursor-pointer',
    },
  },
  {
    id: 'farmer',
    name: 'Farmer',
    description: 'Cultivate land and raise livestock.',
    theme: {
      backgroundColor: 'from-lime-300 to-green-400',
      backgroundImage: 'linear-gradient(to top, #c1dfc4 0%, #deecdd 100%)',
      primaryColor: 'bg-yellow-900',
      textColor: 'text-gray-800',
      icon: Tractor,
      cursor: 'cursor-pointer',
    },
  },
  {
    id: 'physicist',
    name: 'Physicist',
    description: 'Study the fundamental principles of the universe.',
    theme: {
      backgroundColor: 'from-blue-900 to-black',
      backgroundImage: 'linear-gradient(to top, #09203f 0%, #537895 100%)',
      primaryColor: 'bg-teal-400',
      textColor: 'text-white',
      icon: Atom,
      cursor: 'cursor-help',
    },
  },
  {
    id: 'architect',
    name: 'Architect',
    description: 'Design buildings and other structures.',
    theme: {
      backgroundColor: 'from-gray-200 to-gray-300',
      backgroundImage: 'linear-gradient(to top, #e6e9f0 0%, #eef1f5 100%)',
      primaryColor: 'bg-gray-800',
      textColor: 'text-gray-900',
      icon: Building,
      cursor: 'cursor-crosshair',
    },
  },
  {
    id: 'sailor',
    name: 'Sailor',
    description: 'Operate and maintain ships and other vessels.',
    theme: {
      backgroundColor: 'from-cyan-300 to-blue-400',
      backgroundImage: 'linear-gradient(120deg, #84fab0 0%, #8fd3f4 100%)',
      primaryColor: 'bg-blue-800',
      textColor: 'text-white',
      icon: Anchor,
      cursor: 'cursor-pointer',
    },
  },
  {
    id: 'writer',
    name: 'Writer',
    description: 'Create written works, such as books, articles, or scripts.',
    theme: {
      backgroundColor: 'from-amber-50 to-orange-100',
      backgroundImage: 'linear-gradient(to top, #fff1eb 0%, #ace0f9 100%)',
      primaryColor: 'bg-gray-700',
      textColor: 'text-gray-800',
      icon: PenTool,
      cursor: 'cursor-text',
    },
  },
  {
    id: 'musician',
    name: 'Musician',
    description: 'Play one or more musical instruments or sing.',
    theme: {
      backgroundColor: 'from-fuchsia-400 to-purple-500',
      backgroundImage: 'linear-gradient(to right, #fa709a 0%, #fee140 100%)',
      primaryColor: 'bg-black',
      textColor: 'text-white',
      icon: Music,
      cursor: 'cursor-pointer',
    },
  },
];


export const STUDENTS: Student[] = [
  { id: '1', name: 'Alex Johnson', ambition: 'Doctor' },
  { id: '2', name: 'Brenda Smith', ambition: 'Pilot' },
  { id: '3', name: 'Charles Brown', ambition: 'Lawyer' },
  { id: '4', name: 'Diana Miller', ambition: 'Scientist' },
  { id: '5', name: 'Ethan Wilson', ambition: 'Artist' },
  { id: '6', name: 'Fiona Davis', ambition: 'Firefighter' },
  { id: '7', name: 'George Garcia', ambition: 'Astronaut' },
  { id: '8', name: 'Hannah Rodriguez', ambition: 'Teacher' },
  { id: '9', name: 'Ian Martinez', ambition: 'Software Engineer' },
  { id: '10', name: 'Jane Hernandez', ambition: 'Chef' },
];
